### ISSUE TITLE
error while running code

### ISSUE THREAD

**Issue by pooja1807** [opetch/terraform-aws-cli-resource#11]
Error running command '/bin/bash -c 'source ../../../../../modules/terraform-aws-cli-resource/assume_role.sh xxxxxxxxx terraform-transit-network-dev-crud && aws route53 create-vpc-association-authorization --hosted-zone-id xxxxxxxx --vpc VPCRegion=eu-central-1,VPCId=xxxxxx --profile service.cicd-admin-dev-crud1'': exit status 1. Output: The system cannot find the path specified.

script is present at correct path

**Comment by opetch** [comment]
You've not given a huge amount of detail as to the the circumstances in which you're running the module. However I suspect from googling your error message that you're using Windows. I'm afraid this module will only run on a unix (or unix-like) operating system i.e. Linux, OSX. If you're stuck with Windows you could try Windows Subsystem for Linux it should work.
