### ISSUE TITLE
What is source?

### ISSUE THREAD

**Issue by FransUrbo** [opetch/terraform-aws-cli-resource#7]
What is `source = "../../cli_resource"` in the example? Is that the `main.tf` file in the `../../cli_resource` directory?

**Comment by opetch** [comment]
Hi @FransUrbo you make a good point there was not much thought given to the source attribute in the example code, at the time I'd copied some code form my machine for documentation purposes. This code referenced the module on my local filesystem, before it existed in GitHub. However given it is now in GitHub the documentation should show an example that can be used without alteration. I've now updated the README to use the a [GitHub source](https://www.terraform.io/docs/modules/sources.html#github) that should work better for you. If you wish to fix to a specific version/git sha, then please use the `ref` query string parameter, such usage is described in Issue #5

**Comment by opetch** [comment]
addressed in https://github.com/opetch/terraform-aws-cli-resource/commit/8b8c4585911c4e82ae287c76d71561c91ed7332f
